version: '3'
services:

  bot_redis:
    image: redis
    ports:
      - '6379:6379'

  db:
    image: postgres
    environment:
      POSTGRES_DB: tg_bot_futures
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  tg_bot:
    build: .
    depends_on:
      - bot_redis
      - db

