version: '3'
services:

  redis:
    image: redis
    ports:
      - '6379:6379'
    network_mode: host

  db:
    image: postgres
    environment:
      POSTGRES_DB: tg_bot_futures
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: localhost
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  tg_bot:
    build: .
    depends_on:
      - redis
      - db
    network_mode: host

